name: Greeting on variable day

on:
  workflow_dispatch
  
env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-in: ubuntu-latest
    env:
      Greeting: Hello
    steps:
     name: "Say Hello Romm it's Monday"
     run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
     env:
       First_Name: Romm
  
